name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React to GitHub Pages
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          checkout: true
          caching: true
